name: Testing Suite
# This workflow doesn't actually test anything yet.  It creates a release 
# when there is a push to main.

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  create-tag:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    # Don't create a tag...on a tag.
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Tag -- Dry Run
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TAGACTION_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          VERBOSE: true
          DRY_RUN: true

      - name: Create Tag
        uses: anothrNick/github-tag-action@1.36.0
        if: "startsWith(github.ref, 'refs/heads/main')"
        env:
          GITHUB_TOKEN: ${{ secrets.TAGACTION_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          VERBOSE: true